#Script generated by creating a leaner version of ShotDistanceCharts jupyter
#External imports
import pandas as pd 

#Local imports
from GraphingFunctions import GenerateFigure
from ShotVariables import GetVariables

#Initiations
shot_table = pd.read_pickle('shot_table.pkl')
shot_variables = GetVariables()

#Filter the shot table
def FilterTable(shots_table, distance_begin, distance_end):
	if shots_variable.player is not 'all':
		player_table = shots_table.loc[shots_table['PLAYER_NAME'] == shots_variable.player]
	filter_table = player_table.loc[(player_table['SHOTDISTANCE'] >= distance_begin) 
		& (player_table['SHOTDISTANCE'] <= distance_end)]
	return filter_table


filter_table = FilterTable(shot_table, shot_variable.distance_begin, 
	shot_variable.distance_end)

#Check that the dataframe isn't empty and then graph function
if filter_table.shape[0] == 0:
	print('Check player name or distances because this is an empty table')
else:
	GenerateFigure(filter_table, shot_variable)